[package]
name = "backend_backend"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
path = "src/lib.rs"

[dependencies]
candid = "0.9"
ic-cdk = "0.10"
ic-cdk-macros = "0.6"
serde = { version = "1.0", features = ["derive"] }
serde_bytes = "0.11"